### ISSUE TITLE
Does not work with scully 0.0.92

### ISSUE THREAD

**Issue by evolkmann** [gammastream/scully-plugins#7]
Hi, after updating Scully, I noticed that your plugins to not work anymore. Below I attached some stacktrace. I assume it is caused by scully moving to a typescript-based config and it seems like the file https://github.com/scullyio/scully/tree/master/scully/utils is not there anymore...

*Workaround*
Downgrade to `"@scullyio/scully": "0.0.90"` and use a JS-based config.

*Environment*:
```
    "@scullyio/ng-lib": "0.0.22",
    "@scullyio/scully": "0.0.92",
    "@gammastream/scully-plugin-http404": "0.0.1",
    "@gammastream/scully-plugin-sitemap": "0.0.5",
```

*Error Log*
```
> scully --removeStaticDist --nw --showGuessError --scan
/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage
---------
 We encountered an error executing the config file. "/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/scully.my-secret-project-webpage.config.ts"
 Check the error below, and try again later
--------- 
Error: Cannot find module '@scullyio/scully/utils/config'
Require stack:
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@gammastream/scully-plugin-sitemap/bundles/gammastream-scully-plugin-sitemap.umd.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/scully.my-secret-project-webpage.config.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/compileConfig.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/config.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/renderPlugins/launchedBrowser.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/handlers/defaultAction.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/handlers/index.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/index.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/renderPlugins/contentRenderPlugin.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/pluginManagement/systemPlugins.js
- /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/scully.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@gammastream/scully-plugin-sitemap/bundles/gammastream-scully-plugin-sitemap.umd.js:2:114
    at Object.<anonymous> (/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@gammastream/scully-plugin-sitemap/bundles/gammastream-scully-plugin-sitemap.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@gammastream/scully-plugin-sitemap/bundles/gammastream-scully-plugin-sitemap.umd.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/scully.my-secret-project-webpage.config.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/compileConfig.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/config.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/renderPlugins/launchedBrowser.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/handlers/defaultAction.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/handlers/index.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/utils/index.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/renderPlugins/contentRenderPlugin.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/lib/pluginManagement/systemPlugins.js',
    '/Users/enzovolkmann/Projekte/my-secret-project/packages/webpage/node_modules/@scullyio/scully/scully.js'
  ]
}
```

**Comment by evolkmann** [comment]
Probably this can be fixed by using https://github.com/scullyio/scully/blob/master/libs/scully/src/lib/utils/config.ts#L83 instead. I can't promise it, but will try to open a PR today or tomorrow. If someone else fixes it in the meantime, just leave a comment to let me know :)

**Comment by msacket** [comment]
Hi @evolkmann .  I'll take a look.  Can you check to see if you have the latest version of the plugin? Try version 1.0.0.  There've been some updates in the 1.0.0 release that might address this issue.  They are breaking changes in the configuration (due to the Typescript config change).  Updated usage can be found here: https://github.com/gammastream/scully-plugins/blob/master/projects/scully-plugin-sitemap/README.md

**Comment by evolkmann** [comment]
@msacket Yes I will have a look, will give you feedback in the next hour 👍🏻

**Comment by evolkmann** [comment]
@msacket I upgraded both Scully and your plugin to the latest versions and this resolves the issue 👍🏻 Thanks for the hint and sorry for not looking close enough in the first place!
